# workflow の名前です。実行時に表示される
name: Manual workflow 2

# on: アクションが実行されるタイミングを指定
on:
  # 「workflow_dispatch」を指定すると、GitHub上で手動実行できる
  workflow_dispatch:
    # 手動実行時に入力する値を設定
    inputs:
      # 入力項目「name」を設定
      name:
        # 'name' の入力項目のプレースホルダー
        description: 'Person to greet'
        # 明示的に値が提供されない場合のデフォルト値
        default: 'World'
        # ワークフローを実行するために入力が必要
        required: true
        # 入力のデータタイプ
        type: string
      # 入力項目「is-set-farewell-message」を設定
      is-set-farewell-message:
        # 'is-set-farewell-message' のチェックボックスの横に表示される文字
        description: 'Set farewell message'
        # 任意の入力項目
        required: false
        # 入力のデータタイプ
        type: boolean
        
# job: この workflow で実行される処理を記載
jobs:
  # 「greet」という1つ目の job を用意
  greet:
    # job 実行環境の設定
    runs-on: ubuntu-latest

    # steps: 実行されるタスクを設定。上から順番に実行される
    steps:
    # step1の処理名は 「Send greeting」
    - name: Send greeting
      # run: 実行するコマンドを指定できる。
      # 「Send greeting」のstepで実行するコマンド
      run: echo "Hello ${{ inputs.name }}"

    - name: Prepare farewell message
      if: ${{ inputs.is-set-farewell-message }}
      # id: ステップのIDを設定
      id: set-farewell-message
      # 後の step で farewell_message を ${{ steps.set-farewell-message.outputs.farewell-message }} で参照できるようにする
      run: |
        echo "farewell-message=Did you receive the greeting I sent earlier?" >> "$GITHUB_OUTPUT"

    - name: Debug
      if: ${{ inputs.is-set-farewell-message }}
      # ${{ steps.set-farewell-message.outputs.farewell_message }} の値を表示
      # (stepのIDを指定して、"$GITHUB_OUTPUT"に設定された変数を取得)
      # ※それぞれの値の実態がわかるようにechoやcatを実行しています
      run: |
        echo "${{ steps.set-farewell-message.outputs.farewell-message }}"
        
  # 「farewell」という2つ目の job を用意
  farewell:
    # このジョブが実行される前に「greet」jobの完了が必要
    needs: greet

    runs-on: ubuntu-latest

    steps:
    - name: Send farewell
      if: ${{ inputs.is-set-farewell-message }}
      run: echo "Goodbye ${{ inputs.name }}"
