name: Validate Semantic Versioning

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  # 手動実行(セマンティックバージョニングの文字列が入力値)
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter a version (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  validate-tag:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.set-vars.outputs.tag }}

    steps:
      # タグの値の参照方法がイベントごとに異なるため、後続処理で参照方法を統一できるように変数を用意する
      - name: Set Variables Based on Event
        id: set-vars
        run: |
          tag=""
          if [ "${{ github.event_name }}" == "push" ]; then
            tag=${GITHUB_REF#refs/tags/}
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            tag=${{ inputs.version }}
          else
            echo "Error: Unsupported event_name '${{ github.event_name }}'" >&2
            exit 1
          fi
          echo "tag=${tag}" >> $GITHUB_OUTPUT
          echo "tag=${tag}"

      # コードを取得（with で何も指定していない場合は、workflow が動いているリポジトリのコードがgit cloneされる)
      - name: Checkout code
        # 公開されている actions/checkout を使用
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      # カスタムアクションを使って version の文字列をチェック
      - name: Validate Semantic Version (for workflow_dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        # Composite action を使用
        uses: ./.github/actions/validate-semver
        with:
          version: ${{ github.event.inputs.version }}

  call-workflow:
    needs: validate-tag
    uses: ./.github/workflows/validation-finished.yaml
    with:
      tag: ${{ needs.validate-tag.outputs.tag }}
